---
title: "1. Exploratory Data Analysis"
author:
- name: Jonathan Dombrosky
  email: jdombrosky@crowcanyon.org
  attributes:
    corresponding: true
  affiliations: 
  - ref: crow
  - ref: unm
- name: Miranda LaZar
  affiliations: 
  - ref: az
- name: Corrie Hyland
  affiliations: 
  - ref: york
- name: Seth D. Newsome
  affiliations: 
  - ref: unm_bio
affiliations:
  - id: crow
    name: Crow Canyon Archaeological Center
    city: Cortez
    state: CO
  - id: unm
    name: Department of Anthropology, University of New Mexico
    city: Albuquerque
  - id: az
    name: School of Anthropology, University of Arizona
    city: Tucson
  - id: york
    name: Department of Archaeology, University of York
    city: York
  - id: unm_bio
    name: Department of Biology, University of New Mexico
    city: Albuquerque
editor: source
self-contained: true
date: now
date-format: "MMMM D, YYYY h:mm A z"
message: false
warning: false
echo: true
format: html
---

## Libraries
```{r}
library(tidyverse)
library(infer)
library(ggtext)
library(SIBER)
library(ggpubr)
library(cowplot)
library(conflicted)
library(broom)
library(factoextra)
library(ggsignif)
conflict_prefer("filter", "dplyr")
conflict_prefer("select", "dplyr")
```

## Figure 1
```{r}
#| fig-height: 8
#| fig-width: 7

set.seed(1)

individual <- data.frame(
  group = c("Generalist Population - Generalist Individuals", 
            "Generalist Population - Generalist Individuals", 
            "Generalist Population - Generalist Individuals", 
            "Generalist Population - Generalist Individuals", 
            "Generalist Population - Specialist Individuals", 
            "Generalist Population - Specialist Individuals", 
            "Generalist Population - Specialist Individuals", 
            "Generalist Population - Specialist Individuals"),
  individual = c(1, 2, 3, 4, 1, 2, 3, 4),
  mean = c(4.5, 4.8, 5.1, 5.4, 2, 4, 6, 8),
  sd = c(2, 2, 2, 2, 0.5, 0.5, 0.5, 0.5)
)

overall <- data.frame(
  group = c("Generalist Population - Generalist Individuals", 
            "Generalist Population - Specialist Individuals"),
  mean = c(5, 5),
  sd = c(2, 4)
)

overall <- overall |> 
  rowwise() |>
  mutate(x = list(seq(-5, 15, length.out = 1000)),
         dnorm = list(dnorm(x, mean, sd))) |> 
  unnest(cols = c(x, dnorm)) |> 
  mutate(dnorm = dnorm * 12)

individual <- individual |> 
  rowwise() |>
  mutate(x = list(seq(-5, 15, length.out = 1000)),
         dnorm = list(dnorm(x, mean, sd))) |> 
  unnest(cols = c(x, dnorm)) |> 
  mutate(dnorm = case_when(group == "Generalist Population - Generalist Individuals"
                           ~ dnorm * 4,
                           .default = dnorm))

lines <- data.frame(
  group = c("Generalist Population - Generalist Individuals", 
            "Generalist Population - Generalist Individuals", 
            "Generalist Population - Generalist Individuals", 
            "Generalist Population - Specialist Individuals", 
            "Generalist Population - Specialist Individuals", 
            "Generalist Population - Specialist Individuals"),
  x = c(4.5, 2, 2.4, 2, 0, 5.2),
  xend = c(5.5, 8, 8.4, 8, 10, 6.8),
  y = c(0.9, 0.65, 0.25, 0.83, 0.5, 0.2),
  yend = c(0.9, 0.65, 0.25, 0.83, 0.5, 0.2)
  
)

text <- data.frame(
  group = c("Generalist Population - Generalist Individuals", 
            "Generalist Population - Generalist Individuals", 
            "Generalist Population - Generalist Individuals", 
            "Generalist Population - Specialist Individuals", 
            "Generalist Population - Specialist Individuals", 
            "Generalist Population - Specialist Individuals"),
  text = c("BIC", "TNW", "WIC", "BIC", "TNW", "WIC"),
  x = c(5, 5, 5 , 5, 5, 6),
  y = c(1, 0.58, 0.18, 0.78, 0.55, 0.16)
)

fig1a <- ggplot() +
  geom_area(data = overall, aes(x = x, y = dnorm), color = "black", fill = NA,
            linewidth = 1) +
  geom_polygon(data = individual, aes(x = x, y = dnorm, 
                                      group = factor(individual), 
                                      fill = factor(individual)), alpha = 0.3,
               color = "black") +
  geom_segment(data = lines, aes(x = x, xend = xend, y = y, yend = yend), 
               inherit.aes = FALSE) +
  geom_text(data = text, aes(x = x, y = y, label = text), hjust = 0.5, 
            vjust = 0.5) +
  scale_fill_manual(values = alpha(c("#0D0887FF", "#6A00A8FF","#B12A90FF", 
                                     "#E16462FF"), 0.3)) +
  facet_wrap(~ group, scales = "free", ncol = 1) +
  labs(x = "δ-value", y = "Frequency", fill = "Individual") +
  theme_classic() +
  theme(legend.position = "bottom",
        strip.background = element_blank(),
        strip.text = element_text(size = 15, face = "bold"),
        axis.ticks = element_blank(),
        axis.text = element_blank(),
        axis.title = element_text(size = 13, face = "bold"),
        axis.line = element_line(linewidth = 1),
        legend.title = element_text(size = 13, face = "bold"))
```

```{r}
#| fig-height: 8
#| fig-width: 6

specialists <- data.frame(
  group = c(rep(c("Specialist Population - Specialist Individuals", 
                  "Generalist Population - Generalist Individuals",
                  "Generalist Population - Specialist Individuals"), 
                each = 15)),
  individual = c(rep(1:3, times = 15, each = 5)),
  value = c(8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 4, 8, 4, 12, 12, 8, 
            12, 8, 8, 4, 12, 4, 12, 4, 8, 4, 4, 4, 4, 4, 8, 8, 8, 8, 8, 12, 12, 
            12, 12, 12),
  time = c(rep(1:5, times = 9))
)


fig1b <- specialists |> 
  mutate(group = factor(group, levels = c(
           "Specialist Population - Specialist Individuals", 
           "Generalist Population - Generalist Individuals",
           "Generalist Population - Specialist Individuals"))) |> 
  ggplot(aes(x = time, y = value)) +
  #geom_point(size = 8, alpha = 0.3, stat = "unique") +
  geom_point(size = 8, stat = "unique", shape = 21, stroke = 1, 
             color = "black", aes(fill = factor(individual))) +
  geom_line(linewidth = 1, alpha = 0.3, aes(color = factor(individual))) +
  scale_fill_manual(values = alpha(c("#0D0887FF", "#6A00A8FF","#B12A90FF"),
                                   0.3)) +
  scale_color_manual(values = alpha(c("#0D0887FF", "#6A00A8FF","#B12A90FF"),
                                   0.3)) +
  facet_wrap(~ group, ncol = 1) +
  scale_y_continuous(limits = c(2, 14)) +
  labs(x = "Time", y = "δ-value", fill = "Individual", color = "Individual") +
  theme_classic() +
  theme(legend.position = "bottom",
        strip.background = element_blank(),
        strip.text = element_text(size = 15, face = "bold"),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_line(linewidth = 1),
        axis.text.x = element_text(size = 11),
        axis.title = element_text(size = 13, face = "bold"),
        axis.line = element_line(linewidth = 1),
        legend.title = element_text(size = 13, face = "bold"))
```

```{r}
#| fig-height: 8
#| fig.width: 10

plot_grid(fig1a, fig1b, labels = "AUTO", label_colour = "black",  
          label_size = 20, ncol = 2)

ggsave("figs/fig_1.jpg", dpi = 300, height = 8, width = 10)
```

## Import Data
```{r}
my_data <- read.table("data/individual_raptor.txt", 
                      header = TRUE, 
                      fill = TRUE, sep = "\t") |> 
  mutate(D13C = case_when(Tissue == "Bone" ~ 2.7, #Hobson and Clark 1992; Table 2; Quail
                          Tissue == "Liver" ~ 0.2, #Hobson and Clark 1992; Table 2; Quail
                          Tissue == "Muscle" ~ 1.1), #Hobson and Clark 1992; Table 2; Quail
         D15N = case_when(Tissue == "Bone" ~ 2.5, #Hobson and Clark 1992; Table 2; Quail
                          Tissue == "Liver" ~ 2.3, #Hobson and Clark 1992; Table 2; Quail
                          Tissue == "Muscle" ~ 1.0), #Hobson and Clark 1992; Table 2; Quail
         D2H = case_when(Tissue == "Bone" ~ -37.0, #Curras et al. 2018, p. 10
                         Tissue == "Liver" ~ -20.0, #Curras et al. 2018, p. 10
                         Tissue == "Muscle" ~ -37.0, #Curras et al. 2018, p. 10
                         .default = 0),
         d13Cdiet = d13C - D13C,
         d15Ndiet = d15N - D15N,
         d2Hdiet = d2H - D2H)
```

### Prep for SIBER
```{r}
all_tissue <- my_data |> 
  select(Individual, d13Cdiet, d15Ndiet, d2Hdiet) |> 
  mutate(group = "All Tissue")

all_bone <- my_data |> 
  filter(Tissue == "Bone") |> 
  select(Individual, d13Cdiet, d15Ndiet, d2Hdiet) |> 
  mutate(group = "All Bone")

long_bone <- my_data |> 
  filter(Bone_Type == "Long") |> 
  select(Individual, d13Cdiet, d15Ndiet, d2Hdiet) |> 
  mutate(group = "Long Bone")

group_data <- bind_rows(all_tissue, all_bone, long_bone)
```

## Isotopic Range per Individual
### Figure 2
```{r}
diff_plot <- group_data |> 
  drop_na(d13Cdiet) |> 
  group_by(group, Individual) |> 
  summarize(min_c = min(d13Cdiet),
            max_c = max(d13Cdiet),
            min_n = min(d15Ndiet),
            max_n = max(d15Ndiet),
            min_h = min(d2Hdiet),
            max_h = max(d2Hdiet), .groups = "keep") |> 
  mutate(c_diff = abs(max_c - min_c),
         n_diff = abs(max_n - min_n),
         h_diff = abs(max_h - min_h)) |> 
  select(group, Individual, c_diff, n_diff, h_diff) |> 
  pivot_longer(cols = 3:5, names_to = "iso_system", 
               values_to = "diff") |> 
  mutate(iso_system = case_when(str_detect(iso_system, "c_") ~ "<i>δ</i><sup>13</sup>C<sub>diet</sub>",
                                str_detect(iso_system, "n_") ~ "<i>δ</i><sup>15</sup>N<sub>diet</sub>",
                                str_detect(iso_system, "h_") ~ "<i>δ</i><sup>2</sup>H<sub>diet</sub>"))
  
```

```{r}
#| fig-height: 3
#| fig.width: 7.5

diff_plot |> 
  mutate(group = factor(group, levels = c("All Tissue", 
                                          "All Bone", "Long Bone"))) |> 
  ggplot(aes(x = group, y = diff)) +
  geom_jitter(size = 3, alpha = 0.25, width = 0.25, color = "#6A00A8FF") +
  geom_boxplot(size = 0.75, alpha = 0.60, outlier.shape = NA, 
               color = "#0D0887FF") +
  facet_wrap(~ iso_system, scales = "free", nrow = 3, ncol = 3) +
  labs(y = "Range per Individual (‰)",
       x = "Tissue Group") +
  geom_signif(comparisons = list(c("All Tissue", "All Bone"),
                                 c("All Bone", "Long Bone"),
                                 c("All Tissue", "Long Bone")), 
              map_signif_level = TRUE, step_increase = 0.05, vjust = 0.6, 
              tip_length = 0, test.args = list(exact = FALSE)) +
  theme_bw() +
  theme(strip.background = element_blank(),
        strip.text.x = element_markdown(size = 13, face = "bold"),
        axis.title = element_text(size = 11, face = "bold"),
        panel.grid.major.x = element_blank(),
        axis.ticks.x = element_blank())

ggsave("figs/fig_2.jpg", dpi = 300, height = 3, width = 7.5)
```

### Five points of data summary
```{r}
diff_plot |> 
  group_by(iso_system, group) |> 
  reframe(quant = quantile(diff, probs = c(0, 0.25, 0.5, 0.75, 1)),
          quant = round(quant, 2)) |> 
  mutate(prob = rep(c(0, 0.25, 0.5, 0.75, 1), times = 9))

diff_plot |> 
  filter(iso_system %in% c("<i>δ</i><sup>13</sup>C<sub>diet</sub>",
                           "<i>δ</i><sup>15</sup>N<sub>diet</sub>")) |> 
  group_by(iso_system, group) |> 
  summarize(greater_1.5 = sum(diff > 1.5), .groups = "drop") |> 
  mutate(n = 20,
         percent = round(greater_1.5 / n * 100, 2))
```

## Calculate NIDS
```{r}
bone_data <- my_data |> 
  filter(Tissue == "Bone") |> 
  select(d13Cdiet, d15Ndiet)

dist_mat <- dist(bone_data, method = 'euclidean')

hclust_test <- hclust(dist_mat, method = 'average')
```

### Figure 3
```{r}
#| fig-height: 3.5
#| fig.width: 7.5

# NIDS at 1.5‰
cut_NIDS <- cutree(hclust_test, h = 1.5)

nids_plot <- bone_data |> 
  mutate(Individual = factor(cut_NIDS),
         group = "NIDS (1.5‰<sup>2</sup>) Individuals")

# Calculate at what cutoff the correct number of individuals is predicted
cut_func <- function(x){
  cutree(hclust_test, h = x) |> 
    max()
}

map_vec(seq(0, 2, 0.02), cut_func) |> 
  data.frame() |> 
  rename(NIDS = 1) |> 
  mutate(height_cut = seq(0, 2, 0.02))

# NIDS at 0.62‰
cut_NIDS <- cutree(hclust_test, h = 0.62)

nids_20_plot <- bone_data |> 
  mutate(Individual = factor(cut_NIDS),
         group = "NIDS (0.62‰<sup>2</sup>) Individuals")

## Format true number of individuals
true_plot <- my_data |> 
  filter(Tissue == "Bone") |> 
  select(Individual, d13Cdiet, d15Ndiet) |> 
  mutate(Individual = factor(Individual),
         group = "True Individuals")

## Figure 3
bind_rows(nids_plot, nids_20_plot, true_plot) |> 
  mutate(group = factor(group, levels = c("True Individuals",
                                          "NIDS (0.62‰<sup>2</sup>) Individuals",
                                          "NIDS (1.5‰<sup>2</sup>) Individuals"))) |> 
  ggplot(aes(x = d13Cdiet, y = d15Ndiet)) +
  #stat_ellipse(aes(color = Individual), linewidth = 1) +
  #geom_point(size = 3, alpha = 0.5) +
  geom_point(aes(color = Individual), size = 3, alpha = 0.5) +
  #geom_point(color = "black", fill = NA, size = 3, shape = 21, stroke = 0.5) +
  labs(x = "<i>δ</i><sup>13</sup>C<sub>diet</sub> (VPDB, ‰)",
       y = "<i>δ</i><sup>15</sup>N<sub>diet</sub> (AIR, ‰)") +
  facet_wrap(~ group, nrow = 1) +
  scale_color_viridis_d(option = "plasma") +
  guides(color = guide_legend(nrow = 2), override.aes = list(size=5)) +
  theme_bw() +
  theme(strip.background = element_blank(),
        strip.text = element_markdown(size = 11, face = "bold"),
        axis.title.x = element_markdown(size = 11, face = "bold"), 
        axis.title.y = element_markdown(size = 11, face = "bold"),
        axis.text = element_text(size = 10),
        panel.grid.minor = element_blank(),
        legend.position = "bottom",
        legend.title = element_text(size = 8, face = "bold"),
        legend.text = element_text(size = 7))
  
ggsave("figs/fig_3.jpg", dpi = 300, height = 3.5, width = 7.5)
```

## Figure 4
```{r}
samp_nisp <- function(nisp) {
  my_data |> 
    filter(Tissue == "Bone") |> 
    select(Individual, Element,Side, d13Cdiet, d15Ndiet) |> 
    rep_slice_sample(n = nisp, replace = FALSE, reps = 30) |> 
    ungroup() |> 
    mutate(nisp = nisp)
}

count_individ <- function(x) {
  x |> 
    summarize(n = n_distinct(Individual)) |> 
    pull()
}

mni <- function(x) {
  x |> 
    group_by(Element, Side) |> 
    count() |> 
    ungroup() |> 
    arrange(-n) |> 
    slice(1) |> 
    pull(n)
}

dist_mat <- function(x) {
  x |> 
    select(d13Cdiet, d15Ndiet) |> 
    dist(method = 'euclidean')
}

hclust_test <- function(x){
  hclust(x, method = 'average')
}

nids <- function(x){
  cutree(x, h = 1.5) |> 
    max()
}
```

```{r}
set.seed(7495)
random_nisp <- map_dfr(10:175, ~ samp_nisp(.x)) |> 
  select(nisp, replicate, Individual, Element, Side, d13Cdiet, d15Ndiet)
```

```{r}
quant_res <- random_nisp |> 
  group_by(nisp, replicate) |> 
  nest() |> 
  mutate(n_true_ind = map(data, count_individ),
         mni = map(data, mni),
         dist_mat = map(data, dist_mat),
         hclust = map(dist_mat, hclust_test),
         nids = map(hclust, nids)) |> 
  ungroup() |> 
  select(nisp, replicate, n_true_ind, mni, nids) |> 
  unnest(cols = c(n_true_ind, mni, nids))
```

```{r, fig.height=6, fig.width=7}
a <- quant_res |>
  ggplot(aes(x = n_true_ind, y = nids)) +
  geom_point(size = 3, alpha = 0.05, color = "#0D0887FF") +
  stat_cor(aes(label = after_stat(rr.label))) +
  labs(x = "Number of Individuals", y = "NIDS") +
  theme_bw() +
  scale_y_continuous(breaks = c(2, 4, 6, 8)) +
  theme(panel.grid = element_blank(),
        axis.title = element_text(size = 12, face = "bold"))

b <- quant_res |>
  ggplot(aes(x = n_true_ind, y = mni)) +
  geom_point(size = 3, alpha = 0.05, color = "#0D0887FF") +
  stat_cor(aes(label = after_stat(rr.label))) +
  labs(x = "Number of Individuals", y = "MNI") +
  theme_bw() +
  theme(panel.grid = element_blank(),
        axis.title = element_text(size = 12, face = "bold"))

c <- quant_res |>
  ggplot(aes(x = n_true_ind, y = nisp)) +
  geom_point(size = 3, alpha = 0.05, color = "#0D0887FF") +
  stat_cor(aes(label = after_stat(rr.label)), r.accuracy = 0.01, digits = 3) +
  labs(x = "Number of Individuals", y = "NISP") +
  theme_bw() +
  theme(panel.grid = element_blank(),
        axis.title = element_text(size = 12, face = "bold"))

d <- quant_res |>
  ggplot(aes(x = nisp, y = nids)) +
  geom_point(size = 3, alpha = 0.05, color = "#0D0887FF") +
  stat_cor(aes(label = after_stat(rr.label))) +
  labs(x = "NISP", y = "NIDS") +
  theme_bw() +
  scale_y_continuous(breaks = c(2, 4, 6, 8)) +
  theme(panel.grid = element_blank(),
        axis.title = element_text(size = 12, face = "bold"))

e <- quant_res |>
  ggplot(aes(x = nisp, y = mni)) +
  geom_point(size = 3, alpha = 0.05, color = "#0D0887FF") +
  stat_cor(aes(label = after_stat(rr.label)), r.accuracy = 0.01) +
  labs(x = "NISP", y = "MNI") +
  theme_bw() +
  theme(panel.grid = element_blank(),
        axis.title = element_text(size = 12, face = "bold"))

f <- quant_res |>
  ggplot(aes(x = mni, y = nids)) +
  geom_point(size = 3, alpha = 0.05, color = "#0D0887FF") +
  stat_cor(aes(label = after_stat(rr.label))) +
  labs(x = "MNI", y = "NIDS") +
  theme_bw() +
  scale_y_continuous(breaks = c(2, 4, 6, 8)) +
  theme(panel.grid = element_blank(),
        axis.title = element_text(size = 12, face = "bold"))

plot_grid(c, NULL, NULL, b, e, NULL, a, d, f, ncol = 3)

ggsave("figs/fig_4.jpg", dpi = 300, height = 6, width = 7)
```

## SIBER
### 95% Confidence Ellipse Calculations
```{r}
all_tiss <- my_data |>
  dplyr::select(d13Cdiet, d15Ndiet, d2Hdiet, Individual) |>
  dplyr::mutate(community = 1) |>
  dplyr::rename(iso1 = d13Cdiet,
                iso2 = d15Ndiet,
                iso3 = d2Hdiet,
                group = Individual) |> 
  drop_na()

all_bones <- my_data |>
  dplyr::filter(Tissue %in% "Bone") |>
  dplyr::select(d13Cdiet, d15Ndiet, d2Hdiet, Individual) |>
  dplyr::mutate(community = 1) |>
  dplyr::rename(iso1 = d13Cdiet,
                iso2 = d15Ndiet,
                iso3 = d2Hdiet,
                group = Individual)

long_bones <- my_data |>
  dplyr::filter(Bone_Type %in% "Long") |>
  dplyr::select(d13Cdiet, d15Ndiet, d2Hdiet, Individual) |>
  dplyr::mutate(community = 1) |>
  dplyr::rename(iso1 = d13Cdiet,
                iso2 = d15Ndiet,
                iso3 = d2Hdiet,
                group = Individual)
```

#### Carbon and Nitrogen
```{r}
all_kapow_CN <- siberKapow(all_tiss, isoNames = c("iso1", "iso2"), 
                        group = "group", pEll = 0.95) |> 
  pluck("ell.coords") |> 
  mutate(name = "All Tissue")

bone_kapow_CN <- siberKapow(all_bones, isoNames = c("iso1", "iso2"), 
                        group = "group", pEll = 0.95) |> 
  pluck("ell.coords") |> 
  mutate(name = "All Bone")

long_kapow_CN <- siberKapow(long_bones, isoNames = c("iso1", "iso2"), 
                        group = "group", pEll = 0.95) |> 
  pluck("ell.coords") |> 
  mutate(name = "Long Bone")

kapow_CN <- rbind(all_kapow_CN, bone_kapow_CN, long_kapow_CN) |> 
  mutate(group = factor(group),
         name = factor(name, levels = c("All Tissue", "All Bone", "Long Bone")),
         iso_system = "δ<sup>13</sup>C<sub>diet</sub> & δ<sup>15</sup>N<sub>diet</sub>")
```

#### Carbon and Hydrogen
```{r}
all_kapow_CH <- siberKapow(all_tiss, isoNames = c("iso1", "iso3"), 
                        group = "group", pEll = 0.95) |> 
  pluck("ell.coords") |>
  mutate(name = "All Tissue")

bone_kapow_CH <- siberKapow(all_bones, isoNames = c("iso1", "iso3"), 
                        group = "group", pEll = 0.95) |> 
  pluck("ell.coords") |> 
  mutate(name = "All Bone")

long_kapow_CH <- siberKapow(long_bones, isoNames = c("iso1", "iso3"), 
                        group = "group", pEll = 0.95) |> 
  pluck("ell.coords") |> 
  mutate(name = "Long Bone")

kapow_CH <- rbind(all_kapow_CH, bone_kapow_CH, long_kapow_CH) |> 
  mutate(group = factor(group),
         name = factor(name, levels = c("All Tissue", "All Bone", "Long Bone")),
         iso_system = "δ<sup>13</sup>C<sub>diet</sub> & δ<sup>2</sup>H<sub>diet</sub>")
```

```{r}
cn_plot <- kapow_CN |> 
  ggplot(aes(x = X1, y = X2, group = group)) +
  geom_polygon(alpha = 0.4, linewidth = 0.5, color = "black", 
               fill = "#0D0887FF") +
  facet_wrap(~ name, nrow = 3) +
  theme_bw() +
  labs(x = "δ<sup>13</sup>C<sub>diet</sub> (VPDB, ‰)",
       y = "δ<sup>15</sup>N<sub>diet</sub> (AIR, ‰)") +
  theme(legend.position = "none",
        strip.background = element_blank(),
        panel.grid.minor = element_blank(),
        strip.text.x = element_text(size = 13, face = "bold"),
        axis.title.x = element_markdown(size = 11, face = "bold"),
        axis.title.y = element_markdown(size = 11, face = "bold"))
```

```{r}
ch_plot <- kapow_CH |> 
  ggplot(aes(x = X1, y = X2, group = group)) +
  geom_polygon(alpha = 0.4, linewidth = 0.5, color = "black", 
               fill = "#0D0887FF") +
  facet_wrap(~ name, nrow = 3) +
  theme_bw() +
  labs(x = "δ<sup>13</sup>C<sub>diet</sub> (VPDB, ‰)",
       y = "δ<sup>2</sup>H<sub>diet</sub> (VSMOW, ‰)") +
  theme(legend.position = "none",
        strip.background = element_blank(),
        panel.grid.minor = element_blank(),
        strip.text.x = element_text(size = 13, face = "bold"),
        axis.title.x = element_markdown(size = 11, face = "bold"),
        axis.title.y = element_markdown(size = 11, face = "bold"))
```

### Supplemental Figure 1
```{r}
#| fig-height: 7.5
#| fig.width: 8

plot_grid(cn_plot, ch_plot, labels = "AUTO", label_colour = "#4d4d4d",  
          label_size = 20, ncol = 2)

ggsave("figs/supp_fig_1.jpg", dpi = 300, height = 7.5, width = 8)
```

## Individual Specialization (WIC, BIC, TNW, WIC:TNW)
### All Bone
```{r}
my_data_bone <- my_data |> 
  filter(Tissue == "Bone")
```

```{r}
# Supplemental Table 1
my_data_bone|> 
  group_by(Individual) |> 
  summarize(mean_d13C_ind = mean(d13Cdiet),
            var_d13C_ind = var(d13Cdiet), 
            mean_d15N_ind = mean(d15Ndiet),
            var_d15N_ind = var(d15Ndiet)) |>
  ungroup() |> 
  summarize(wic_d13C = mean(var_d13C_ind),
            bic_d13C = var(mean_d13C_ind),
            wic_d15N = mean(var_d15N_ind),
            bic_d15N = var(mean_d15N_ind)) |> 
  mutate(tnw_d13C = wic_d13C + bic_d13C,
         tnw_d15N = wic_d15N + bic_d15N,
         wictnw_d13C = wic_d13C / tnw_d13C,
         wictnw_d15N = wic_d15N / tnw_d15N) |> 
  pivot_longer(cols = everything(),
               names_to = c("metric", "iso_system"),
               names_sep = "_") |> 
  mutate(metric = factor(metric, levels = c("wic", "bic", "tnw", "wictnw")),
         metric = case_when(metric == "wictnw" ~ "wic:tnw",
                            .default = metric)) |> 
  pivot_wider(names_from = metric, values_from = value)

# Check TNW
my_data |> 
  filter(Tissue == "Bone") |> 
  summarise(tnw_d13C = var(d13Cdiet),
            tnw_d15N = var(d15Ndiet))
```

```{r}
my_data_bone |> 
  summarize(d13C_range = diff(range(d13Cdiet)),
            d15N_range = diff(range(d15Ndiet)))
```

```{r}
#| fig-height: 3.5
#| fig.width: 7.5

my_data_bone |> 
  group_by(Individual) |> 
  summarize(wic_d13C_ind = var(d13Cdiet), 
            wic_d15N_ind = var(d15Ndiet), .groups = "drop") |> 
  mutate(tnw_d13C = var(my_data_bone$d13Cdiet),
         tnw_d15N = var(my_data_bone$d15Ndiet),
         wictnw_d13C = wic_d13C_ind / tnw_d13C,
         wictnw_d15N = wic_d15N_ind / tnw_d15N) |> 
  select(Individual, wictnw_d13C, wictnw_d15N) |> 
  pivot_longer(cols = 2:3, 
               names_to = c("metric", "iso_system"),
               names_sep = "_") |> 
  mutate(iso_system = case_when(iso_system == "d13C" ~ 
                                  "<i>δ</i><sup>13</sup>C<sub>diet</sub> (VPDB, ‰)",
                                iso_system == "d15N" ~ "<i>δ</i><sup>15</sup>N<sub>diet</sub> (AIR, ‰)")) |> 
  ggplot(aes(x = value)) +
  geom_density(fill = "#0D0887FF", alpha = 0.5) +
  facet_wrap(~iso_system) +
  theme_bw() +
  labs(x = "WIC:TNW", 
       title = "Distribution of WIC:TNW Across 20 Cooper's Hawk Individuals") +
  theme(strip.background = element_blank(),
        strip.text = element_markdown(size = 11, face = "bold"))

ggsave("figs/supp_fig_5.jpg", dpi = 300, height = 3.5, width = 7.5)
```
